# Site settings
title: 坂井
SEOTitle: Guang1234567的博客 | Guang1234567 的博客 | Guang1234567 Blog
header-img: img/home-bg-art.jpg
email: Guang1234567pro@gmail.com
description: "关于前端与设计、Android | Guang1234567，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 Guang1234567 的个人博客，与你一起发现更大的世界。"
keyword: "Guang1234567, 鬼栈, @Guang1234567, @lihansey, Guang1234567 的博客, Guang1234567的博客, Guang1234567 Blog, 博客, 个人网站, 互联网, Web, Android, 前端, 设计"
url: "https://guang1234567.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     lihansey
zhihu_username:     lihansey
github_username:    Guang1234567
twitter_username:   lihansey
#facebook_username:  lihansey
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md","third_part","lightbox/README.md","jekyll-search/README.md","tctip/README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    disable: true
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    wrap:              div
    line_numbers:      inline
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Connect to a locally built Jekyll Server using mobile devices in the LAN
# https://stackoverflow.com/questions/16608466/connect-to-a-locally-built-jekyll-server-using-mobile-devices-in-the-lan
host: 0.0.0.0

# Disqus settings
disqus_username: Guang1234567

# Netease setttings
netease_comment: false

# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_username: MTAyMC8zMjMwMS84ODYy

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-7'            # Format: UA-xxxxxx-xx
ga_domain: guang1234567.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-Guang1234567.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "Piasy RxJava 高阶翻译",
        href: "https://piasy.github.io/AdvancedRxJava/tags/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]
